### PR TITLE
Add text in header

### PR DESCRIPTION
**Pull request by Anshika-98**

### CODE REVIEW

**Review by redpepper-nag — APPROVED** [review]
Looks perfect

**Comment by VGmt** [comment]
@Anshika-98 

Commits should be a little more specific.

Content = Concise summary of what happened.

For example, in your commit "added text", it could have been: "added gym name", or "added gym name to Dashboard's title view".

It doesn't have to be overly specific, but enough for us to understand what you did, and for you to remember what you did.

**Review by VGmt — APPROVED** [review]
Looks perfect

**Review by VGmt — CHANGES_REQUESTED** [review]
PR title must be more specific

**Pull request merged**
